import { useEffect, useState } from 'react';
import axios from 'axios';

export default function NFTJSON({ address }){
    const [nftJson, setNftJson] = useState([]);

    // Retrieve a users NFTs based on their connected wallet address
    useEffect(() => {
        if (address){
            axios(`http://localhost:4000/nft/${address}`)
            .then(({ data }) => {
                setNftJson(data.result);
        })}
    }, [address])

    // Parse the metadata included in the NFT to get the car NFT image originally generated by a user
    const getImageUrl = (metadata) => {
        try {
          const parsedMetadata = JSON.parse(metadata);
          return parsedMetadata.image;
        } catch (error) {
          console.error("Error parsing metadata:", error);
          return null;
        }
      };

    // Parse the metadata in the NFT to get the Make, Model, and Year of the users vehicles
    const getCarMMY = (metadata) => {
        try {
            const parsedMetadata = JSON.parse(metadata);
            let MMY = ""
            for (let details of parsedMetadata.attributes){
                MMY += (details.value + " ")
            }
            return MMY
        } catch (error) {
            console.error("Error parsing metadata:", error);
            return null;
          }
    }

    // Get the NFT data and display it on the frontend
    const singleNFT = nftJson.map(item => {
        if (item.name === "DIMO Vehicle ID"){
            const imageUrl = getImageUrl(item.metadata);
            const carMMY = getCarMMY(item.metadata)
            return(
                <div>
                    <h3>Vehicle Info: </h3>
                    <div>
                        <p>Car MMY: {carMMY}</p>
                        <p>Token ID: {item.token_id}</p>
                        <p>Metadata: {item.metadata}</p>
                        <p>Owner of: {item.owner_of}</p>
                        <p>Token Address: {item.token_address}</p>
                        <p>Token URI: {item.token_uri}</p>
                        <p>Associated NFT Image:</p>
                        <img className="nft-image" src={imageUrl}></img>
                    </div>
                </div>
            )
        }
    })

    return(
        <>
            {nftJson ? singleNFT : <></>}
        </>
    )
}